query GetDestinations($first: Int = 10, $search: String = "") {
  destinations(first: $first, where: { search: $search }) {
    edges {
      node {
        id
        uri
        title
        slug
        excerpt
        genreDestination {
          nodes {
            name
          }
        }
        spotsDetails {
          spotDetails
        }
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        destinations {
          labels
          fullAddress {
            details
            portal
            lat
            lng
          }
          areas {
            edges {
              node {
                id
                name
              }
            }
          }
        }
      }
    }
  }
}
